var cities = [{
  value: 'https://h5.youzan.com/v2/feature/VlLbMob5rL',
  label: '佛山市'
}, {
  value: 'https://h5.youzan.com/v2/feature/7LwY8vq39V',
  label: '广州市'
}, {
  value: 'https://h5.youzan.com/v2/feature/GiekK4VVe4',
  label: '台山市'
}, {
  value: 'default',
  label: '中山市'
}, {
  value: 'default',
  label: '珠海市'
}, {
  value: 'default',
  label: 'test_myRebase'
}, {
  value: 'default',
  label: 'mytest2'
}, {
  value: 'default',
  label: '加多一条mytest'
}, {
  value: 'default',
  label: 'test1'
}, {
  value: 'default',
  label: 'test2'
}, {
  value: 'default',
  label: '再加一条mytest2'
}]